# SPDX-License-Identifier: CC0-1.0
name: Lint GitHub Actions workflows
on:
  pull_request:
    paths:
      - '.github/workflows/**.yml'
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: raven-actions/actionlint@v1
